services:
  app:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}:latest
    container_name: cri-study-linux-web
    expose:
      - "8000"
    volumes:
      - /mnt/efs/data:/app/data
    environment:
      - DB_PATH=/app/data/app.db
      - CONFIG_PATH=/app/data/config.json
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: cri-study-linux-web-app-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro
      - /mnt/efs/certs:/etc/letsencrypt:ro
    depends_on:
      - app
    restart: unless-stopped
