
name: Deploy to EC2

on:
  push:
    branches:
      - main
    workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}
    
    - name: Resolve EC2 hostname to IP
      id: resolve_ec2
      run: |
        EC2_HOSTNAME=${{ vars.EC2_HOSTNAME }}
        EC2_HOST=$(getent hosts "$EC2_HOSTNAME" | awk '{print $1}')
        echo "EC2_HOST=${EC2_HOST}" >> "$GITHUB_OUTPUT"

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ vars.EC2_USER }}@${{ steps.resolve_ec2.outputs.EC2_HOST }} "
          cd /var/www/cri-study-linux-web-app &&
          git pull &&
          /var/www/cri-study-linux-web-app/venv/bin/pip install -r requirements.txt &&
          sudo systemctl restart fastapi_app
        "
