
name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    
    - name: Resolve EC2 hostname to IP
      id: resolve_ec2
      run: |
        EC2_HOSTNAME=${{ vars.EC2_HOSTNAME }}
        EC2_HOSTNAME=$(getent hosts "$EC2_HOSTNAME" | awk '{print $1}')
        echo "EC2_HOSTNAME=${EC2_HOSTNAME}" >> "$GITHUB_OUTPUT"

    - name: Clone or pull repository
      run: |
        ssh -o StrictHostKeyChecking=no ${{ vars.DEPLOY_USERNAME }}@${{ steps.resolve_ec2.outputs.EC2_HOSTNAME }} \
          "cd /var/www/cri-study-linux-web-app &&
          if [ ! -d .git ]; then
            git clone https://github.com/${{ github.repository }}.git .
          else
            git pull
          fi"

    - name: Install dependencies
      run: |
        ssh -o StrictHostKeyChecking=no ${{ vars.DEPLOY_USERNAME }}@${{ steps.resolve_ec2.outputs.EC2_HOSTNAME }} \
          "cd /var/www/cri-study-linux-web-app &&
          if [ ! -d .venv ]; then
            python3.11 -m venv .venv
          fi && ls -la &&
          .venv/bin/pip install -r requirements.txt"

    - name: Configure environment
      run: |
        ssh -o StrictHostKeyChecking=no ${{ vars.DEPLOY_USERNAME }}@${{ steps.resolve_ec2.outputs.EC2_HOSTNAME }} \
          "echo 'ADMIN_INITIAL_PASSWORD=${{ secrets.ADMIN_INITIAL_PASSWORD }}' | sudo tee /etc/fastapi_app.env > /dev/null &&
          sudo chmod 600 /etc/fastapi_app.env"

    - name: Configure nginx
      run: |
        ssh -o StrictHostKeyChecking=no ${{ vars.DEPLOY_USERNAME }}@${{ steps.resolve_ec2.outputs.EC2_HOSTNAME }} \
          "sudo sed -i 's/DOMAIN_NAME/${{ vars.EC2_HOSTNAME }}/' /etc/nginx/conf.d/default.conf"

    - name: Restart services
      run: |
        ssh -o StrictHostKeyChecking=no ${{ vars.DEPLOY_USERNAME }}@${{ steps.resolve_ec2.outputs.EC2_HOSTNAME }} \
          "sudo systemctl daemon-reload &&
          sudo systemctl restart fastapi_app &&
          sudo systemctl start nginx"

    - name: Setup SSL Certificate
      run: |
        ssh -o StrictHostKeyChecking=no ${{ vars.DEPLOY_USERNAME }}@${{ steps.resolve_ec2.outputs.EC2_HOSTNAME }} "
          if [ ! -d /etc/letsencrypt/live/${{ vars.EC2_HOSTNAME }} ]; then
            sudo certbot --nginx -d ${{ vars.EC2_HOSTNAME }} --non-interactive --agree-tos -m webmaster@${{ vars.EC2_HOSTNAME }}
          fi
        "

    - name: Upload fallback page to S3
      run: |
        ssh -o StrictHostKeyChecking=no ${{ vars.DEPLOY_USERNAME }}@${{ steps.resolve_ec2.outputs.EC2_HOSTNAME }} "
          aws s3 cp /var/www/cri-study-linux-web-app/fallback/index.html s3://${{ vars.FALLBACK_S3_BUCKET }}/index.html
        "
